# IRIS DATASET

This project uses the classic Iris dataset to demonstrate unsupervised machine learning using the K-means clustering algorithm. The objective is to group Iris flower samples into clusters based on their physical attributes, such as sepal length, sepal width, petal length, and petal width and evaluate whether the algorithm can separate the different species based on their similarities.

In [ ]:
import os
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn import datasets

In [ ]:
sns.set()

## Load and Explore Data

Importing Iris flower data set and observing the available parameters.

In [ ]:
data = pd.read_csv("iris.csv")
data.keys()

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [15]:
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Need to observe the diferent Species availabe in this dataset.

In [18]:
species = data['Species'].unique()
print(f"Species: {species}")

Species: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

Need to add a target value based on the Species name.

For this case:

    0 - Iris-setosa

    1 - Iris-versicolor

    2 - Iris-virginica

In [21]:
species_map = {
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2}

data["target_name"] = data["Species"].map(species_map)
data.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,target_name
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0